/oak:
  ros__parameters:
    camera:
      i_enable_imu: true
      i_enable_ir: false
      i_floodlight_brightness: 0
      i_pipeline_type: RGBD
      i_usb_speed: SUPER_PLUS
      i_nn_type: none
    imu:
      i_get_base_device_timestamp: false # TODO: Set these true for more accurate timestamps?
    left:
      i_board_socket_id: 1
      i_get_base_device_timestamp: false
      i_fps: 30.0
      i_height: 800
      i_publish_topic: false
      i_resolution: '800'
      i_width: 1280
    rgb:
      i_board_socket_id: 0
      i_disable_node: true
      i_enable_preview: false
      i_publish_topic: false
      i_simulate_from_topic: true
    right:
      i_board_socket_id: 2
      i_get_base_device_timestamp: false
      i_fps: 30.0
      i_height: 800
      i_publish_topic: false
      i_resolution: '800'
      i_width: 1280
    stereo:
      i_align_depth: false # TODO: In future could be true if i_board_socket_id is respected
      i_get_base_device_timestamp: false
      i_output_disparity: false
      i_board_socket_id: 2
      i_height: 800
      i_lr_check: true
      i_subpixel: true
      i_input_width: 1280
      i_input_height: 800
      i_width: 1280
      i_publish_left_rect: true
      i_publish_right_rect: true
      i_right_rect_enable_feature_tracker: true
    use_sim_time: false